// <auto-generated />
using System;
using AtivosApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtivosApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708060352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AtivosApi.Domain.Entities.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoIdentificacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioCadastroId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdentificacao")
                        .IsUnique();

                    b.HasIndex("UsuarioCadastroId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("AtivosApi.Domain.Entities.Emprestimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetorDestino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioSolicitanteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("UsuarioSolicitanteId");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("AtivosApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cpf = "00000000000",
                            Email = "admin@corporate.org.br",
                            NomeCompleto = "Administrador TI",
                            SenhaHash = "hashed_password",
                            Setor = "TI"
                        });
                });

            modelBuilder.Entity("AtivosApi.Domain.Entities.Ativo", b =>
                {
                    b.HasOne("AtivosApi.Domain.Entities.Usuario", "UsuarioCadastro")
                        .WithMany("AtivosCadastrados")
                        .HasForeignKey("UsuarioCadastroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("AtivosApi.Domain.Entities.Emprestimo", b =>
                {
                    b.HasOne("AtivosApi.Domain.Entities.Ativo", "Ativo")
                        .WithMany("Emprestimos")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtivosApi.Domain.Entities.Usuario", "UsuarioSolicitante")
                        .WithMany("Emprestimos")
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("AtivosApi.Domain.Entities.Ativo", b =>
                {
                    b.Navigation("Emprestimos");
                });

            modelBuilder.Entity("AtivosApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AtivosCadastrados");

                    b.Navigation("Emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
